name: CustomEnchant
main: pup\customenchants\Main
author: pup
api: 5.0.0
version: 1.1.0

permissions:
  enchant.command:
    default: op
    description: Base enchant command
  enchant.command.add:
    default: op
    description: Add an enchant to an item
  enchant.command.remove:
    default: op
    description: Remove an enchant from an item