# ========================
#      CONFIG VERSION
# ========================
config_version: 1.0.0

# ========================
#        RARITIES
# ========================
rarities:
  COMMON:
    weight: 50 #Chance of getting from a ce book
    display_color: "§f"
    enabled: true

  UNCOMMON:
    weight: 25
    display_color: "§a"
    enabled: true

  RARE:
    weight: 15
    display_color: "§9"
    enabled: true

  EPIC:
    weight: 10
    display_color: "§5"
    enabled: true

  LEGENDARY:
    weight: 5
    display_color: "§6"
    enabled: true

  MASTERY:
    weight: 3
    display_color: "§3"
    enabled: true

  HEROIC:
    weight: 0
    display_color: "§4"
    enabled: true
# ========================
#         MESSAGES
# ========================
messages:
  proc_messages:
    enabled: true
    format: "§e{enchant_name} §fhas activated! (Level: {level})"
# =======================
#      SETTINGS
# =======================
max_level: true #Caps /enchanter enchanting at the max level
enchant_lore:
  header: "§r§dEnchantments: "  # The header line
  entry_format: " §r§8» §r{color}{name} {level}"  # Format for each enchant
  sort_by_rarity: true  # Whether to sort enchants by rarity
  roman_numerals: = true # Whether to enable roman numerals as level showcase